### ISSUE TITLE
Custom keyboard options when responding

### ISSUE THREAD

**Issue by phils-hub** [EdJoPaTo/telegraf-stateless-question#3]
Currently there is no possibility to specify a custom keyboard or a custom inline keyboard for making it easier to respond (e.g. numbers keyboard when specifying time), as you can when using the standard reply from Telegraf.

**Comment by EdJoPaTo** [comment]
I think this is the same as #1?

**Comment by phils-hub** [comment]
Yeah i guess it is. Il shift the discussion to #1 then.
